name = "tech-trend-archiver"
main = "src/index.ts"
compatibility_date = "2025-12-25"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[[d1_databases]]
binding = "D1_DB"
database_name = "tech-trend-archiver"
database_id = "37894c30-f160-47dc-bd83-7b5d24bda13c"

[triggers]
crons = ["0 3 * * *", "0 15 * * *"]
